/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.yannicklamprecht.spigot.tools

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.github.yannicklamprecht.spigottools.greeting' plugin.
 */
class SpigotToolsPluginTest {
    @Test
    fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.github.yannicklamprecht.spigot.tools")

        // Verify the result
        assertNotNull(project.tasks.findByName("setup"))
        assertNotNull(project.tasks.findByName("cleanup"))
    }
}
